export enum degrerealisation{
    EMINTERCEPTE='EM INTERCEPTE AVANT ATTEINTE DU PATIENT',
    EMNONINTERCEPTE='EM NON INTERCEPTE',
    EVENEMENTPORTEURRISQUE='EVENEMENT PORTEUR DE RISQUE',
    JENESAISPAS='JE NE SAIS PAS ',
}