export enum etapedesurvenu{
    PRESCRIPTION='PRESCRIPTION',
    DISPENSATION='DISPENSATION',
    TRANSPORT='TRANSPORT',
    ADMINISTRATION='ADMINISTRATION',
    SUIVIETREEVALUATION='SUIVI ET REEVALUATION',
    JENESAISPAS='JE NE SAIS PAS',
    AUTRE ='AUTRE',
}