export enum service {
   SELECTIONNERSERVICE='SELECTIONNER_UN_SERVICE',
    CHIRURGIE='CHIRURGIE',
    MEDICOTECHNIQUE='MEDICO-TECHNIQUE',
    GERONTOLOGIE='GERONTOLOGIE',
    MEDECINE='MEDECINE',
    MEREENFANT='MERE ENFANT',
    PLATEAUTECHNIQUE='PLATEAUTECHNIQUE',

}